/*
 * SentinelDB RESTful API
 * Read more at https://docs.sentineldb.io
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ExternalEncryptionResult
 */

public class ExternalEncryptionResult {
  @JsonProperty("ciphertext")
  private String ciphertext = null;

  @JsonProperty("lookupKeys")
  private List<String> lookupKeys = null;

  public ExternalEncryptionResult ciphertext(String ciphertext) {
    this.ciphertext = ciphertext;
    return this;
  }

   /**
   * Get ciphertext
   * @return ciphertext
  **/
  @ApiModelProperty(value = "")
  public String getCiphertext() {
    return ciphertext;
  }

  public void setCiphertext(String ciphertext) {
    this.ciphertext = ciphertext;
  }

  public ExternalEncryptionResult lookupKeys(List<String> lookupKeys) {
    this.lookupKeys = lookupKeys;
    return this;
  }

  public ExternalEncryptionResult addLookupKeysItem(String lookupKeysItem) {
    if (this.lookupKeys == null) {
      this.lookupKeys = new ArrayList<>();
    }
    this.lookupKeys.add(lookupKeysItem);
    return this;
  }

   /**
   * Get lookupKeys
   * @return lookupKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getLookupKeys() {
    return lookupKeys;
  }

  public void setLookupKeys(List<String> lookupKeys) {
    this.lookupKeys = lookupKeys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalEncryptionResult externalEncryptionResult = (ExternalEncryptionResult) o;
    return Objects.equals(this.ciphertext, externalEncryptionResult.ciphertext) &&
        Objects.equals(this.lookupKeys, externalEncryptionResult.lookupKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ciphertext, lookupKeys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalEncryptionResult {\n");
    
    sb.append("    ciphertext: ").append(toIndentedString(ciphertext)).append("\n");
    sb.append("    lookupKeys: ").append(toIndentedString(lookupKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

