/*
 * SentinelDB RESTful API
 * Read more at https://docs.sentineldb.io
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRawValue;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * UserRequest
 */

public class UserRequest {
  @JsonProperty("attributes")
  @JsonRawValue
  private String attributes = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("roles")
  private List<String> roles = null;

  @JsonProperty("status")
  private String status = null;

  /**
   * Gets or Sets systemRoles
   */
  public enum SystemRolesEnum {
    ADMIN("DATASTORE_ADMIN"),
    
    USER_ADMIN("DATASTORE_USER_ADMIN"),
    
    VIEWER("DATASTORE_VIEWER"),
    
    USER_VIEWER("DATASTORE_USER_VIEWER");

    private String value;

    SystemRolesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SystemRolesEnum fromValue(String text) {
      for (SystemRolesEnum b : SystemRolesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("systemRoles")
  private List<SystemRolesEnum> systemRoles = null;

  @JsonProperty("username")
  private String username = null;

  public UserRequest attributes(String attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public String getAttributes() {
    return attributes;
  }

  public void setAttributes(String attributes) {
    this.attributes = attributes;
  }

  public UserRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserRequest roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public UserRequest addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public UserRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public UserRequest systemRoles(List<SystemRolesEnum> systemRoles) {
    this.systemRoles = systemRoles;
    return this;
  }

  public UserRequest addSystemRolesItem(SystemRolesEnum systemRolesItem) {
    if (this.systemRoles == null) {
      this.systemRoles = new ArrayList<>();
    }
    this.systemRoles.add(systemRolesItem);
    return this;
  }

   /**
   * Get systemRoles
   * @return systemRoles
  **/
  @ApiModelProperty(value = "")
  public List<SystemRolesEnum> getSystemRoles() {
    return systemRoles;
  }

  public void setSystemRoles(List<SystemRolesEnum> systemRoles) {
    this.systemRoles = systemRoles;
  }

  public UserRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRequest userRequest = (UserRequest) o;
    return Objects.equals(this.attributes, userRequest.attributes) &&
        Objects.equals(this.email, userRequest.email) &&
        Objects.equals(this.password, userRequest.password) &&
        Objects.equals(this.roles, userRequest.roles) &&
        Objects.equals(this.status, userRequest.status) &&
        Objects.equals(this.systemRoles, userRequest.systemRoles) &&
        Objects.equals(this.username, userRequest.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, email, password, roles, status, systemRoles, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRequest {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    systemRoles: ").append(toIndentedString(systemRoles)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

