/*
 * SentinelDB RESTful API
 * Read more at https://logsentinel.com/sentineldb/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.logsentinel.sentineldb.model.generic;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Generic Record entity, allowing to set a custom type body
 */
public class Record<T> implements Serializable {
    private T body = null;

    private LocalDateTime created = null;

    private UUID datastoreId = null;

    private UUID id = null;

    private UUID ownerId = null;

    private String pseudoId = null;

    private String pseudoOwnerId = null;

    private String type = null;

    private LocalDateTime updated = null;

    private Integer version = null;

    public T getBody() {
        return body;
    }

    public void setBody(T body) {
        this.body = body;
    }

    public LocalDateTime getCreated() {
        return created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public UUID getDatastoreId() {
        return datastoreId;
    }

    public void setDatastoreId(UUID datastoreId) {
        this.datastoreId = datastoreId;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(UUID ownerId) {
        this.ownerId = ownerId;
    }

    public String getPseudoId() {
        return pseudoId;
    }

    public void setPseudoId(String pseudoId) {
        this.pseudoId = pseudoId;
    }

    public String getPseudoOwnerId() {
        return pseudoOwnerId;
    }

    public void setPseudoOwnerId(String pseudoOwnerId) {
        this.pseudoOwnerId = pseudoOwnerId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public LocalDateTime getUpdated() {
        return updated;
    }

    public void setUpdated(LocalDateTime updated) {
        this.updated = updated;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

}
