/*
 * SentinelDB RESTful API
 * Read more at https://logsentinel.com/sentineldb/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.BatchRequestItem;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BatchApi
 */
@Ignore
public class BatchApiTest {

    private final BatchApi api = new BatchApi();

    
    /**
     * Deletes a batch of entities. If an error occurs, all operations are rolled back
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void batchDeleteTest() throws ApiException {
        List<BatchRequestItem> batchRequestItems = null;
        UUID datastoreId = null;
        api.batchDelete(batchRequestItems, datastoreId);

        // TODO: test validations
    }
    
    /**
     * Inserts a batch of entities. If an error occurs, all operations are rolled back
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void batchInsertTest() throws ApiException {
        List<BatchRequestItem> batchRequestItems = null;
        UUID datastoreId = null;
        api.batchInsert(batchRequestItems, datastoreId);

        // TODO: test validations
    }
    
}
