/*
 * SentinelDB RESTful API
 * Read more at https://sentineldb.logsentinel.com/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.Datastore;
import com.logsentinel.sentineldb.model.Record;
import java.util.UUID;
import com.logsentinel.sentineldb.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DatastoreApi
 */
@Ignore
public class DatastoreApiTest {

    private final DatastoreApi api = new DatastoreApi();

    
    /**
     * Gets records by datastore with pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecordsByDatastoreTest() throws ApiException {
        UUID datastoreId = null;
        UUID pseudoId = null;
        String actor = null;
        Integer pageNumber = null;
        Integer pageSize = null;

        List<Record> response = api.getRecordsByDatastore(datastoreId, actor, pageNumber, pageSize, pseudoId);
        // TODO: test validations
    }
    
    /**
     * Gets users by datastore with pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersByDatastoreTest() throws ApiException {
        UUID datastoreId = null;
        String actor = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        UUID pseudoId = null;
        List<User> response = api.getUsersByDatastore(datastoreId, actor, pageNumber, pageSize, pseudoId);

        // TODO: test validations
    }
    
    /**
     * Gets a list of datastores
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDatastoresTest() throws ApiException {
        List<Datastore> response = api.listDatastores();

        // TODO: test validations
    }
    
}
