/**
 * SentinelDB RESTful API
 * Read more at https://sentineldb.logsentinel.com/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.Record;
import com.logsentinel.sentineldb.model.User;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DatastoreApi
 */
public class DatastoreApiTest {

    private final DatastoreApi api = new DatastoreApi();

    
    /**
     * Gets records by datastore with pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecordsByDatastoreTest() throws ApiException {
        String datastoreId = null;
        String actor = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        // List<Record> response = api.getRecordsByDatastore(datastoreId, actor, pageNumber, pageSize);

        // TODO: test validations
    }
    
    /**
     * Gets users by datastore with pagination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersByDatastoreTest() throws ApiException {
        String datastoreId = null;
        String actor = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        // List<User> response = api.getUsersByDatastore(datastoreId, actor, pageNumber, pageSize);

        // TODO: test validations
    }
    
}
