/*
 * SentinelDB RESTful API
 * Read more at https://docs.sentineldb.io
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.ExternalEncryptionResult;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExternalEncryptionApi
 */
@Ignore
public class ExternalEncryptionApiTest {

    private final ExternalEncryptionApi api = new ExternalEncryptionApi();

    
    /**
     * Decrypt any data (represented as base64-encoded string) for a given entity type, id and datastore
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void decryptDataTest() throws ApiException {
        String ciphertext = null;
        UUID datastoreId = null;
        String entityId = null;
        String entityType = null;
        UUID id = null;
        UUID organizationId = null;
        String secret = null;
        String response = api.decryptData(ciphertext, datastoreId, entityId, entityType, id, organizationId, secret);

        // TODO: test validations
    }
    
    /**
     * Encrypt any data (represented as string) for a given entity type, id and datastore
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void encryptDataTest() throws ApiException {
        UUID datastoreId = null;
        String entityId = null;
        String entityType = null;
        String fieldName = null;
        String payload = null;
        UUID id = null;
        UUID organizationId = null;
        String secret = null;
        ExternalEncryptionResult response = api.encryptData(datastoreId, entityId, entityType, fieldName, payload, id, organizationId, secret);

        // TODO: test validations
    }
    
}
