/*
 * SentinelDB RESTful API
 * Read more at https://docs.sentineldb.io
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessageApi
 */
@Ignore
public class MessageApiTest {

    private final MessageApi api = new MessageApi();

    
    /**
     * Sends Email to user by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendEmailTest() throws ApiException {
        UUID datastoreId = null;
        String senderEmail = null;
        String subject = null;
        UUID templateId = null;
        UUID recipientRecordId = null;
        String recipientRecordProperty = null;
        UUID recipientUserId = null;
        UUID recordId = null;
        api.sendEmail(datastoreId, senderEmail, subject, templateId, recipientRecordId, recipientRecordProperty, recipientUserId, recordId);

        // TODO: test validations
    }
    
    /**
     * Sends Email to user using SendGrid custom templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendEmailWithDynamicTemplateTest() throws ApiException {
        UUID datastoreId = null;
        String dynamicTemplateId = null;
        UUID recordId = null;
        String senderEmail = null;
        UUID recipientRecordId = null;
        String recipientRecordProperty = null;
        UUID recipientUserId = null;
        api.sendEmailWithDynamicTemplate(datastoreId, dynamicTemplateId, recordId, senderEmail, recipientRecordId, recipientRecordProperty, recipientUserId);

        // TODO: test validations
    }
    
    /**
     * Sends SMS to user by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendSMSTest() throws ApiException {
        UUID datastoreId = null;
        UUID templateId = null;
        UUID recipientRecordId = null;
        String recipientRecordProperty = null;
        UUID recipientUserId = null;
        UUID recordId = null;
        Object response = api.sendSMS(datastoreId, templateId, recipientRecordId, recipientRecordProperty, recipientUserId, recordId);

        // TODO: test validations
    }
    
}
