/*
 * SentinelDB RESTful API
 * Read more at https://logsentinel.com/sentineldb/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.PseudonymizationKey;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PseudonymizationApi
 */
@Ignore
public class PseudonymizationApiTest {

    private final PseudonymizationApi api = new PseudonymizationApi();

    
    /**
     * Creates a pseudonymization key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        UUID datastoreId = null;
        String description = null;
        PseudonymizationKey response = api.create(datastoreId, description);

        // TODO: test validations
    }
    
    /**
     * Deletes a pseudonymization key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        UUID id = null;
        api.delete(id);

        // TODO: test validations
    }
    
    /**
     * Gets a pseudonymization key by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        UUID id = null;
        PseudonymizationKey response = api.get(id);

        // TODO: test validations
    }
    
    /**
     * Gets a pseudonymization keys by datastoreId
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lististTest() throws ApiException {
        UUID datastoreId = null;
        List<PseudonymizationKey> response = api.listist(datastoreId);

        // TODO: test validations
    }
    
}
