/*
 * SentinelDB RESTful API
 * Read more at https://sentineldb.logsentinel.com/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.Record;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecordsApi
 */
@Ignore
public class RecordsApiTest {

    private final RecordsApi api = new RecordsApi();

    
    /**
     * Creates a record
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRecordTest() throws ApiException {
        String body = null;
        UUID datastoreId = null;
        String actorId = null;
        UUID ownerId = null;
        String type = null;
        Record response = api.createRecord(body, datastoreId, actorId, ownerId, type);

        // TODO: test validations
    }
    
    /**
     * Deletes an existing record
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRecordTest() throws ApiException {
        UUID recordId = null;
        String actorId = null;
        Object response = api.deleteRecord(recordId, actorId);

        // TODO: test validations
    }
    
    /**
     * Gets record by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecordTest() throws ApiException {
        UUID recordId = null;
        String actorId = null;
        Record response = api.getRecord(recordId, actorId);

        // TODO: test validations
    }
    
    /**
     * Gets concrete record version
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecordVersionTest() throws ApiException {
        UUID recordId = null;
        Integer version = null;
        String actorId = null;
        Record response = api.getRecordVersion(recordId, version, actorId);

        // TODO: test validations
    }
    
    /**
     * Gets all record versions by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecordVersionsTest() throws ApiException {
        UUID recordId = null;
        List<Integer> response = api.getRecordVersions(recordId);

        // TODO: test validations
    }
    
    /**
     * Updates record
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRecordTest() throws ApiException {
        Record record = null;
        UUID recordId = null;
        String actorId = null;
        Record response = api.updateRecord(record, recordId, actorId);

        // TODO: test validations
    }
    
    /**
     * Updates a record&#39;s owner
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRecordOwnerTest() throws ApiException {
        UUID ownerId = null;
        UUID recordId = null;
        String actorId = null;
        Record response = api.updateRecordOwner(ownerId, recordId, actorId);

        // TODO: test validations
    }
    
}
