/*
 * SentinelDB RESTful API
 * Read more at https://sentineldb.logsentinel.com/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.Record;
import java.util.UUID;
import com.logsentinel.sentineldb.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * Search records
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchRecordsTest() throws ApiException {
        UUID datastoreId = null;
        Object request = null;
        String type = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        List<Record> response = api.searchRecords(datastoreId, request, type, 0L, pageNumber, pageSize, 0L);

        // TODO: test validations
    }
    
    /**
     * Search users
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchUsersTest() throws ApiException {
        UUID datastoreId = null;
        Object request = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        List<User> response = api.searchUsers(datastoreId, request, 0L, pageNumber, pageSize, 0L);

        // TODO: test validations
    }
    
}
