/*
 * SentinelDB RESTful API
 * Read more at https://docs.sentineldb.io
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.sentineldb.api;

import com.logsentinel.sentineldb.ApiException;
import com.logsentinel.sentineldb.model.MessageTemplate;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplatesApi
 */
@Ignore
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    
    /**
     * createTemplate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTemplateTest() throws ApiException {
        String content = null;
        String name = null;
        MessageTemplate response = api.createTemplate(content, name);

        // TODO: test validations
    }
    
    /**
     * deleteTemplate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTemplateTest() throws ApiException {
        UUID templateId = null;
        api.deleteTemplate(templateId);

        // TODO: test validations
    }
    
    /**
     * template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void templateTest() throws ApiException {
        String templateName = null;
        MessageTemplate response = api.template(templateName);

        // TODO: test validations
    }
    
    /**
     * updateTemplate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTemplateTest() throws ApiException {
        String content = null;
        String name = null;
        UUID templateId = null;
        api.updateTemplate(content, name, templateId);

        // TODO: test validations
    }
    
}
